### ISSUE TITLE
[Bug] 无法在taro rn 中使用

### ISSUE THREAD

**Issue by Engimaz** [alovajs/adapter-taro#4]
### Reproduction Link

https://github.com/Engimaz/taro-app-demo.git

### alova Version

2.0.9

### Describe the Bug

我在taro框架中开发移动端引入了adapter-taro。使用rn模式，在启动时报错， 似乎是cjs导出的ReactHook有问题。

### Reproduce Steps
1.依赖下载
```
yarn install
```

2. 项目启动

```
yarn dev:rn
```

有如下报错 
```
 BUNDLE  ./index.js 

error: Error: Unable to resolve module alova/react from /Users/enigma/IdeaProjects/mhr-app-taro/node_modules/@alova/adapter-taro/dist/alova-adapter-taro.common.cjs: alova/react could not be found within the project or in these directories:
  node_modules
  12 | var Taro = require('@tarojs/taro');
  13 | var shared = require('@alova/shared');
> 14 | var ReactHook = require('alova/react');
     |                          ^
  15 |
  16 | var l2CacheAdapter = {
  17 |     get(key) {
    at ModuleResolver.resolveDependency (/Users/enigma/IdeaProjects/mhr-app-taro/node_modules/@react-native/community-cli-plugin/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:148:15)
    at DependencyGraph.resolveDependency (/Users/enigma/IdeaProjects/mhr-app-taro/node_modules/@react-native/community-cli-plugin/node_modules/metro/src/node-haste/DependencyGraph.js:235:43)
    at /Users/enigma/IdeaProjects/mhr-app-taro/node_modules/@react-native/community-cli-plugin/node_modules/metro/src/lib/transformHelpers.js:160:21
    at resolveDependencies (/Users/enigma/IdeaProjects/mhr-app-taro/node_modules/@react-native/community-cli-plugin/node_modules/metro/src/DeltaBundler/buildSubgraph.js:42:25)
    at visit (/Users/enigma/IdeaProjects/mhr-app-taro/node_modules/@react-native/community-cli-plugin/node_modules/metro/src/DeltaBundler/buildSubgraph.js:83:30)
    at async Promise.all (index 1)
    at visit (/Users/enigma/IdeaProjects/mhr-app-taro/node_modules/@react-native/community-cli-plugin/node_modules/metro/src/DeltaBundler/buildSubgraph.js:92:5)
    at async Promise.all (index 1)
    at visit (/Users/enigma/IdeaProjects/mhr-app-taro/node_modules/@react-native/community-cli-plugin/node_modules/metro/src/DeltaBundler/buildSubgraph.js:92:5)
    at async Promise.all (index 12)
```

**Comment by JOU-amjs** [comment]
[troubleshooting - 在 React-Native 中要注意什么](https://alova.js.org/zh-CN/tutorial/project/troubleshooting#%E5%9C%A8-react-native-%E4%B8%AD%E8%A6%81%E6%B3%A8%E6%84%8F%E4%BB%80%E4%B9%88)

**Comment by Engimaz** [comment]
> [troubleshooting - 在 React-Native 中要注意什么](https://alova.js.org/zh-CN/tutorial/project/troubleshooting#%E5%9C%A8-react-native-%E4%B8%AD%E8%A6%81%E6%B3%A8%E6%84%8F%E4%BB%80%E4%B9%88)

谢谢 这个解决了我的问题
